# Generated by Django 4.2.3 on 2023-07-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
